### ISSUE TITLE
Expose options to CLI

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/sentinel5dl#1]
Right now, the CLI tool has a bunch of hardcoded search parameters used for downloading Sentinel-5p data files. While this works for testing purposes, it would be quite nice to evolve this into an actual useful command-line tool by simply exposing a fea of the search options.

The hard-coded options can be found here:

https://github.com/emissions-api/sentinel5dl/blob/3921a5ebcdc64d38dc9e01ed728b0dd8effbddd8/sentinel5dl/__main__.py#L16-L25

Maybe we could use something like [argparse](https://docs.python.org/3/library/argparse.html) to provide the search options via the command line.

**Comment by cfletemier** [comment]
I'd like to work on this if that's ok.

**Comment by lkiesow** [comment]
Sure, go ahead. That would be great.

**Comment by cfletemier** [comment]
How do we want to handle the polygon arguments? We could require a 5 element tuple containing 2 element tuples each with the one included now as an example or default. It'll make for a large command line command but it'll work.

**Comment by lkiesow** [comment]
Some alternatives:

- The simplest way would be to just require the user to provide a [polygon in WKT form](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry)
- A simple and relatively user-friendly way would be to just ask for two coordinates which could be the top-left and bottom-right coordinates of a rectangle. From that, it would be easy to construct a polygon. This would probably serve most purposes.
- Finally, we could ask for a [GeoJSON containing a polygon](https://tools.ietf.org/html/rfc7946#section-3.1.6). That way, we could easily provide complex shapes but it is also more complex and probably means more dependencies. Not sure if that is what we necessarily want since this is mainly meant as a library.

Anyway, I'll leave the decision up to you.

**Comment by cfletemier** [comment]
Makes sense, your first suggestion is what I was lookin at when mulling this over so I'll go with that and then add that link in help text. Thanks!

**Comment by lkiesow** [comment]
Hey @cfletemier, how are things going? Are you making progress with this? Do you need any help?

**Comment by cfletemier** [comment]
@lkiesow I am making project, just been an eventful week. I should have a PR for this soon.

**Comment by lkiesow** [comment]
No problem, thanks for the update. Let us know if you run into any problems.

**Comment by cfletemier** [comment]
@lkiesow please let me know if this is sufficient or if more validation is needed. I'll be happy to revise!
