### ISSUE TITLE
Consider switching to readthedocs

### ISSUE THREAD

**Issue by lkiesow** [emissions-api/sentinel5dl#25]
…since they support multiple versions and in the current form, our documentation infrastructure does not. Other alternative suggestions are welcome.

**Comment by lkiesow** [comment]
Read the Docs fails to install the dependencies since pycURL is based on a C-library which is not allowed to be installed. We could work around this but it might be easier to stay with GitHub pages and introduce versioning there. We may be able to use [sphinxcontrib-versioning](https://github.com/sphinx-contrib/sphinxcontrib-versioning) for that.

**Comment by shaardie** [comment]
@lkiesow Do we need to support multiple versions in documentation. Although it would be nice, we only support the latest version anyway.

**Comment by tibroc** [comment]
via @lkiesow: switching to readthedocs would mean either getting the c-dependencies into the rtd base-image or mocking them. This is the reason why we decided not to change to readthedocs.
