### ISSUE TITLE
downloading data

### ISSUE THREAD

**Issue by Meresmata** [emissions-api/sentinel5dl#69]
Hi I currently tried to download data both in shell(windows) and python. 

Both times I get the Error: (60, 'SSL certificate problem: unable to get local issuer certificate')

What might be the reason? I tried it on another pc today (linux shell). There everything was fine. Did the api change? Or am I blogged because I already downloaded something?

**Comment by shaardie** [comment]
Hej, there is a problem with the certificate pool in Windows, but you can use the certificates from [certifi](https://pypi.org/project/certifi/). This can be enable by running sentinel5dl with `--use-certifi` on Windows as described in the help.

**Comment by Meresmata** [comment]
Thanks,
 also found out that this seams to be a Windows problem. With your advice I set 
`sentinel5dl.ca_info = certifi.where()`

and it worked out fine.
